content/current/contents.lr

Feel free to reject/close this if you don't agree. The way the ticket prices were written with parenthesis was a little confusing to me. This is just how it would make more sense to me. Your call @CAM-Gerlach!

Disambiguated ticket prices

---

content/faq/contents.lr

Updated outdated info in the FAQ

Updated FAQ with new info

---

content/faq/contents.lr

Switch "glass" and "in" in the current text: "so long as they are not kept glass in containers"

Fix typo in 'Are alcoholic drinks allowed' section

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Updates the mission timer and the information to reflect the delay to NASA Crew-2.

Update site with Crew-2 delay

---

content/current/contents.lr

Update site for second round of SLS rollout trips

---

content/current/contents.lr

Update site for third trip to see SLS rolled out on the pad

---

assets/static/js/custom-scripts.js
content/current/contents.lr

See title.
I'll merge once @EvanDotPro is able to set the timer on the booking site.

Update site for SLS pre-WDR sunset pad trip

---

content/current/contents.lr
content/details/contents.lr
content/faq/contents.lr

Fix several typos that were found on the tickets page, and update some outdated sections on the Details page.

Fix typos on tickets page for Artemis 1 and update outdated Details page

---

content/current/contents.lr

Temporarily disable launch ticket sales due to no more boat space

---

content/current/contents.lr

Close off Artemis 1 launch viewing tickets and update others

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Just like it says on the tin. Ticket sales currently held due to weather, though.

Update website for Falcon Heavy USSF-52 X-37B launch

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update for the 24 hour launch delay, and add the Stripe link now that we are formally offering tickets

Update for USSF-52 X-37B OTV-7 delay & offering tickets

---

content/current/contents.lr

Cancel the USSF-52 trip due to boat engine trouble

---

content/current/contents.lr

Add payment link for USSF-52 and update text accordingly

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update the USSF-52 launch time from 7 PM ET/ 00 UTC to 8 PM ET / 01 UTC, and disable booking for now due to being sold out.

Update USSF-52 launch time and close booking due to being sold out

---

content/current/contents.lr

Close reservations for Ax-3 at capacity limit

---

assets/static/js/custom-scripts.js
content/current/contents.lr
content/details/contents.lr

Update Axiom-3 for 1-day delay to Jan 18 & clarify scrub policy

---

content/current/contents.lr

Add information about newely booked boat & clarify situation

---

content/current/contents.lr

Switch to standby phone booking only.

Update site to reflect IFT-3 sold out

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Also fix a few typos from the first go around.

Update site for second launch attempt of final Delta IV / NROL-70

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update site for Starship Flight 4

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Also make a few minor improvements to WhatsApp wording.

Update site to reflect IFT-4 launch delay to June 6

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Add initial info for Falcon Heavy GOES-U mission

---

content/current/contents.lr

Update website for last tickets & pre-launch for GOES-U

---

content/current/contents.lr

Also update pre-launch trip info to include evening time

Add info & link for the Canaveral Princess on GOES-U

---

content/current/contents.lr

Currently tentative until we get closer to launch

Add initial information for Starship IFT5 launch

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update for the new date and add the ticket link and countdown

Update site for IFT5 Oct 13 date and ticket availability

---

README.md
assets/static/js/custom-scripts.js
content/contents.lr
content/current/contents.lr
star_fleet_tours.lektorproject

Update for Flight 6, replace Mailchimp & obfuscate WA URI

---

content/current/contents.lr

Update Flight 6 page after first boat is sold out

---

content/current/contents.lr

Update page with waiting list after second IFT6 boat sellout

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update website for Flight 6 delay to Tuesday Nov 19

---

.github/workflows/build.yaml
assets/static/js/custom-scripts.js
content/current/contents.lr

Add payment link and update other info for IFT7

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Convey uncertainty of Starship IFT7 launch date

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update Starship IFT-7 to new Jan 11 launch date and time

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update site for Jan 13 IFT7 date and slim down text

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update site for IFT7 delay to Jan 15

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Add delay to the Jan 16 and close tickets

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Add Starship IFT 8

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update Flight 8 launch date to March 3

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update site for immediately after Starship IFT8 May 3 scrub

---

content/current/contents.lr

Add Starship IFT8 Take 2 payment link

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update IFT8 launch date to Thursday March 6

---

content/current/contents.lr

Conclude the Starship IFT8 mission

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Add information we have so far about launch, our plans and the remaining steps to get there.

Update site to initial version for SpaceX Starship Flight 10

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update WhatsApp link and IFT10 latest flight status

---

assets/static/js/custom-scripts.js
content/current/contents.lr

Update site for third attempt of Starship IFT10
